### ISSUE TITLE
data folder

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [Bachfischer/COMP90042-Rumour-Detection-on-Twitter#1]
Hi,
I am running 01_rumour_detection_bertweet.ipynb but in the data folder, there is no train.data.jsonl file. How can I access this file? Thanks

**Comment by Bachfischer** [comment]
Hi, 

unfortunately I can't share the `train.data.jsonl` dataset because it is prohibited under Twitter's API Terms of Service. 

As an alternative, you may want to look into this dataset: https://www.kaggle.com/c/nlp-getting-started

(I also built a BERTweet model for that: https://www.kaggle.com/matthiasbachfischer/disaster-tweets-bertweet)
